### ISSUE TITLE
Delete this

### ISSUE THREAD

**Issue by bluepilledgreat** [WaviestBalloon/FastLogExtractor#1]
Anything written in Rust needs to be deleted

**Comment by TheGreatSageEqualToHeaven** [comment]
@bluepilledgreat I agree Matt.

**Comment by bluepilledgreat** [comment]
@WaviestBalloon Any progress on this? Could you also delete your Github account while you're at it?

**Comment by WaviestBalloon** [comment]
> Could you also delete your Github account while you're at it?

![image](https://github.com/WaviestBalloon/FastLogExtractor/assets/31796727/ec0e2c91-c4e9-45b6-aa88-35f25cadc149)

**Comment by bluepilledgreat** [comment]
> > Could you also delete your Github account while you're at it?
> 
> ![image](https://private-user-images.githubusercontent.com/31796727/337405536-ec0e2c91-c4e9-45b6-aa88-35f25cadc149.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc3MDE0MzEsIm5iZiI6MTcxNzcwMTEzMSwicGF0aCI6Ii8zMTc5NjcyNy8zMzc0MDU1MzYtZWMwZTJjOTEtYzRlOS00NWI2LWFhODgtMzVmMjVjYWRjMTQ5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjA2VDE5MTIxMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQzMWJkNjI5ZmQxYWRlNTBhODY4ZDYzZDgwMDdmMTFkNmY1ZDM2NDY0MzI1YjE0ZTQyZDllMzBiN2VkMWVjM2ImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.igrGCAyWYILvTvgA9IhyOU3wFRMz6gOxOVPk5eZDH8s)

Delete your github account

**Comment by bluepilledgreat** [comment]
@WaviestBalloon Bud you better reopen this
